name: Continuous Integration

on:
  push:
    branches:
    - master
    paths:
      - "gotham-server/**"
      - "gotham-utilities/**"
      - "integration-tests/**"
      - "gotham-client/Cargo.toml"
      - "Cargo.toml"

  pull_request:
    branches:
    - master
    paths:
      - "gotham-server/**"
      - "gotham-utilities/**"
      - "integration-tests/**"
      - "gotham-client/Cargo.toml"
      - "Cargo.toml"


jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  build-and-test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: lints
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
#      - run: cargo build --release

      - name: Unit tests
        run:  cargo test --all -- --nocapture



